filter:
    excluded_paths:
        - 'js/*'
        - 'l10n/*'
        - 'tests/*'
        - 'worker/*'

imports:
    - php

tools:
    external_code_coverage:
        runs: 1
        timeout: 600 # Timeout in seconds: 2 hours
